// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// centers
NumericVector centers(const NumericMatrix& triangs);
RcppExport SEXP gapski_centers(SEXP triangsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type triangs(triangsSEXP);
    __result = Rcpp::wrap(centers(triangs));
    return __result;
END_RCPP
}
