// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// centers
NumericVector centers(const NumericMatrix& triangs);
RcppExport SEXP gapski_centers(SEXP triangsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type triangs(triangsSEXP);
    rcpp_result_gen = Rcpp::wrap(centers(triangs));
    return rcpp_result_gen;
END_RCPP
}
