# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculating centres of radii of Delauney circumcircles
centers <- function(triangs) {
    .Call('gapski_centers', PACKAGE = 'gapski', triangs)
}

